services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres_server
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: learnJava!2025
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    command: ["postgres", "-c", "max_connections=200"]
    networks:
      - carpooling_network
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 15

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - carpooling_network
      - db_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"   # HTTP UI
      - "8000:8000"   # optional (Edge/agent tunnel)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  carpooling_network:
    external: true
  db_network:
    driver: bridge

volumes:
  pgdata:
  pgadmin_data:
  portainer_data:

