spring.application.name=car-pooling-vehicles-api

server.port=8081
# DATABASE CONFIG (Docker-ready)
spring.datasource.url=jdbc:postgresql://localhost:5432/vehicles_db
spring.datasource.username=postgres
spring.datasource.password=learnJava!2025
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate (opcional)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
# Security Config for JWT token
security.token.secret="15fffccd-dfbc-4580-868d-e55d4c400264Carpooling"
security.token.issuer="carpooling"

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.circuitbreaker.resilience4j.enabled=true
resilience4j.circuitbreaker.instances.identity.slidingWindowSize=10
resilience4j.circuitbreaker.instances.identity.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.identity.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.identity.failureRateThreshold=50
resilience4j.circuitbreaker.instances.identity.waitDurationInOpenState=10s

management.endpoints.web.exposure.include=health,info,metrics,prometheus,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
management.metrics.tags.application=car-pooling-vehicles-api
