spring.application.name=car-pooling-gps-api
server.port=8085

spring.datasource.url=jdbc:postgresql://db_server:5432/gps_db
spring.datasource.username=postgres
spring.datasource.password=learnJava!2025
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/
eureka.instance.prefer-ip-address=true

gps.nominatim.base-url=https://nominatim.openstreetmap.org
gps.nominatim.user-agent=IPCB-CarPooling/1.0
