spring.application.name=car-pooling-frontend
server.port=3002

# Thymeleaf
spring.thymeleaf.cache=true

# API Gateway (Docker) - Internal service name
api.gateway.url=http://cloud-gateway:8888

# Eureka Client (Docker)
eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=car-pooling-frontend
